### ISSUE TITLE
USBC PD issue

### ISSUE THREAD

**Issue by qxtman** [tylercreeves/PadPal#1]
Hey, I don't have mine in hand yet, but going off of Schematic V3, 
At present, you do not have any resistors on the CC1 or CC2 lanes of the USB C connector. 
I believe that those resistors are required when using a propper USB C supply. 
Attaching a 5.1k pull down resistor to each pin will (should) re enable USBC to USBC functionality. 
I have mine on the way, I will see if I can update my model to prove it out. 

There are more details with USB C PD, about forcing lower maximum current, but I do not have enough details on that at present.

**Comment by tylercreeves** [comment]
Thanks qxtman!!
Just created a new branch for motor control board V4 where I'm trying to implement the USB-C to USB-C functionality.
I took a V3 board and did a hack job at adding the resistors as described. Interestingly, it worked via USB-C ports on both my power banks, but did not work from a USB-C wall powered power source. IDK whats going on there but it really only has to work with power banks so that left me satisfied enough to implement the changes in a new board.
I'll be uploading the V4 board Gerber files later today, and I should have 20 V4 boards coming in the mail soon (about a week). I'll merge the branch back with main if everything pans out after testing.

**Comment by tylercreeves** [comment]
V4 Boards are in and undergoing testing. They appear to work flawlessly : ) I plan to be merging the Motor_Control_Board_V4 branch with main soon.

**Comment by tylercreeves** [comment]
I think its solved, V4 board have been working great and snuck them into a few customer Pad-Pals with no issues. I'll be closing this issue for now unless something else pops up.
